apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: tekton-tasks-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: TektonTasks is the Schema for the tektontasks API
      displayName: Tekton Tasks
      kind: TektonTasks
      name: tektontasks.tektontasks.kubevirt.io
      version: v1alpha1
  description: operator, which deploys kubevirt-tekton-tasks
  displayName: tekton-tasks-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - kubevirt
  - VM
  - tekton
  links:
  - name: Kubevirt Tekton Tasks Operator
    url: https://tekton-tasks-operator.domain
  maturity: alpha
  provider:
    name: kubevirt.io
    url: kubevirt.io
  version: 0.0.0
