apiVersion: tektontasks.kubevirt.io/v1alpha1
kind: TektonTasks
metadata:
  name: tektontasks-sample
  namespace: kubevirt
spec:
  featureGates:
    deployTektonTaskResources: true
  pipelines:
    namespace: kubevirt
  tasks:
    namespace: kubevirt
